spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zvukiznanje?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=CET&AllowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
  cache:
    jcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB
server:
  port: 8080

auth-key: YouShallNotPass

jwt:
  secret: b3ZvIGplIHRlc3QgbWFsbyBkdXplIHJpamVjaQ==
  validityInMinutes: 20

fs:
  base-url: \Users\PC\Desktop\ZvukIznanjeFiles\